services:

    paymill.form.type:
        class: %paymill.form.type.class%
        arguments:
            payment.cart.wrapper: @payment.cart.wrapper
        tags:
            - { name: form.type, alias: paymill_view }

    paymill.transaction.wrapper:
        class: %paymill.transaction.wrapper.class%
        arguments:
            paymill.private.key: %paymill.private.key%
            paymill.public.key: %paymill.public.key%


    paymill.manager:
        class: %paymill.manager.class%
        arguments:
            payment.event.dispatcher: @payment.event.dispatcher
            payment.transaction.wrapper: @paymill.transaction.wrapper
            paymill.api.endpoint: %paymill.api.endpoint%
            payment.cart.wrapper: @payment.cart.wrapper
            payment.currency.wrapper: @payment.currency.wrapper
            payment.order.wrapper: @payment.order.wrapper

    paymill.twig.extension:
        class: %paymill.twig.extension.class%
        arguments:
            paymill.public.key: %paymill.public.key%
            form.factory: @form.factory
            payment.currency.wrapper: @payment.currency.wrapper
        tags:
            - { name: twig.extension }

    paymill.routes.loader:
        class: %paymill.routes.loader.class%
        arguments:
            paymill.controller.route: %paymill.controller.route%
        tags:
            - { name: routing.loader }